name: pan_app
description: Piattaforma Agro-Network (PAN) — chat + marketplace
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:

  # Auth & utilità
  google_sign_in:
  geolocator:
  geocoding:
  url_launcher:
  image_picker:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
